services:
  - type: web
    name: stock-price-predictor
    env: docker
    region: ohio  # Change this to your preferred region
    plan: free
    branch: main
    healthCheckPath: /docs
    envVars:
      - key: PORT
        value: 8000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    autoDeploy: true
